### ISSUE TITLE
Test hangs if more than 4 different nats listeners are used

### ISSUE THREAD

**Issue by gjuh** [micronaut-projects/micronaut-nats#145] opened 2021-04-15 15:13 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
Run unit test in the attached project.
In the unit test i am calling 5 different client functions which at the end call 5 listeners.

### Expected Behaviour
All client function should get response and test should finish.

### Actual Behaviour
Stops at first unit test and hangs. There is no response from the client.

If I disable one of the listeners 4 tests work fine. Fifth one can't work because we disabled the listener.
To me it looks like there is a limit how many listeners there can be (5). Is there some limit to the number of listeners?

### Environment Information

- **Operating System**: Ubuntu 20.10
- **Micronaut Version:** 2.2.3
- **JDK Version:** JDK 8

### Example Application
https://github.com/micronaut-projects/micronaut-nats/files/6318891/natsdemo.zip

**Comment by grimmjo** [comment] 2021-05-13 15:09
Hey @gjuh,

I couldn't reproduce this issue. The tests have been executed successfully with your demo project. I've tested it under Windows and Ubuntu. I will close this issue. Reopen it, if you have further information about your issue.

**Closed by grimmjo** 2021-05-13 15:09 UTC
